/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prg2hs17_gr3_dnb.view;

import java.awt.event.ActionEvent;

/**
 *
 * @author Daniel Ouwehand
 */
public class Credits2 extends javax.swing.JFrame {
    
    MenuFrame menuFrame;

    /**
     * Creates new form Credits2
     */
    public Credits2() {
        initComponents();
        this.setSize(540,580);
        this.setResizable(false);
        back.addActionListener((ActionEvent e) -> {
            backPressed();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Credits");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 190, 63, 33);

        jLabel7.setText("1. Name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(240, 280, 40, 14);

        jLabel8.setText("2. Name");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(240, 320, 70, 14);

        jLabel10.setText("4. Name");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(240, 400, 70, 14);

        jLabel9.setText("3. Name");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(240, 360, 80, 14);

        back.setText("jButton1");
        getContentPane().add(back);
        back.setBounds(450, 520, 73, 23);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel Ouwehand\\Desktop\\Sackgasse_4cdab2cd7305a.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 540, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void backPressed() {
        MenuFrame menuFrame = new MenuFrame();
        menuFrame.setVisible(true);
        this.setVisible(false);

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Credits2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Credits2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Credits2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Credits2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Credits2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
